### ISSUE TITLE
08.machine_translation has error when is_generating=True

### ISSUE THREAD

**Issue by lujiaying** [PaddlePaddle/book#346]
Error Info:
```
I0718 14:56:51.086495 26798 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
Traceback (most recent call last):
  File "train.py", line 235, in <module>
    main()
  File "train.py", line 201, in main
    is_generating, beam_size)
  File "train.py", line 132, in seq_to_seq_net
    max_length=max_length)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 3803, in beam_search
    is_generating=True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 3498, in recurrent_group
    layer_outs = step(*in_args)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 3793, in __real_step__
    predict = gipt.after_real_step(step(*args))
  File "train.py", line 65, in gru_decoder_with_attention
    error_clipping_threshold=100.0))
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 362, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 973, in fc_layer
    **ExtraLayerAttribute.to_kwargs(layer_attr))
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3191, in Layer
    return layer_func(name, **xargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 1583, in __init__
    super(FCLayer, self).__init__(name, 'fc', size, inputs=inputs, **xargs)
TypeError: __init__() got an unexpected keyword argument 'error_clipping_threshold'
```

**Comment by lcy-seso** [comment]
- 您好，请问您是如何安装 Paddle的呢？
- 这个错误存在与早前的develop 分支，这个PR https://github.com/PaddlePaddle/Paddle/pull/2757 已经fix了这个bug。
- 一个简单的快速的解决方法是您可以直接clone 最新的develope 分支，替换这个PR中修改过的文件。

**Comment by lujiaying** [comment]
- 我使用的百度云的深度学习实例，paddle的版本好像是0.10.0
- 我试一下这个解决方法哈

**Comment by lujiaying** [comment]
按照替换PR中修改过的文件，不再报此错误。
咨询了百度云的开发者，BDL深度学习实例放的是paddle的release版本

**Comment by lcy-seso** [comment]
嗯~ 造成这一问题也是由于前几日更新了Book中机器翻译的教程，增加了`error_clipping`参数，但需要paddle 代码也一起更新。应该是两者没有一起更新。
