### ISSUE TITLE
02.recognize_digits/client/client.py run error

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/book#461]
```bash
python client.py 
Traceback (most recent call last):
  File "client.py", line 19, in <module>
    r = requests.post("http://0.0.0.0:8000", json={'img': data})
  File "/Library/Python/2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 442, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x108ae8c10>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

Maybe missing http services? or tips.

**Comment by jacquesqiao** [comment]
this client is used in our PaddlePaddle client docker image
https://github.com/PaddlePaddle/book/blob/develop/serve/README.md
