### ISSUE TITLE
0.14版本下 08.machine_translation infer无法运行

### ISSUE THREAD

**Issue by zhuantouer** [PaddlePaddle/book#609]
```
Traceback (most recent call last):
  File "infer.py", line 210, in <module>
    main(use_cuda)
  File "infer.py", line 205, in main
    decode_main(False)  # Beam Search does not support CUDA
  File "infer.py", line 147, in decode_main
    translation_ids, translation_scores = decode(context)
  File "infer.py", line 112, in decode
    level=0)
TypeError: beam_search() got multiple values for keyword argument 'end_id'
```

**Comment by zhuantouer** [comment]
0.14的beam_search参数改了，官方文档api参数说明还没更新。。。
有点坑，每次都要去翻源码。。。。

**Comment by qshi95** [comment]
> 0.14的beam_search参数改了，官方文档api参数说明还没更新。。。
> 有点坑，每次都要去翻源码。。。。

请问应该是怎么修改呢
