### ISSUE TITLE
机器翻译infer报错

### ISSUE THREAD

**Issue by chopperm** [PaddlePaddle/book#858]
"The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "seq2seq.py", line 343, in <module>
    main(use_cuda)
  File "seq2seq.py", line 338, in main
    infer(use_cuda)
  File "seq2seq.py", line 319, in infer
    seq_ids = exe.run(prog, feed=data, fetch_list=[predict_seqs])[0]

用的是demo代码，未做修改，paddle版本1.6.1，python版本2.7.13

**Comment by heavengate** [comment]
麻烦问下具体用的那个demo，还有麻烦给出全量的报错信息

**Comment by chopperm** [comment]
demo代码是代码库文件book/08.machine_translation/seq2seq.py
全量报错如下：
![image](https://user-images.githubusercontent.com/17583439/83998605-8c753680-a993-11ea-8aef-f4a995bde35f.png)
![image](https://user-images.githubusercontent.com/17583439/83998627-98f98f00-a993-11ea-9268-5420dacaa55d.png)

**Comment by chopperm** [comment]
参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/beginners_guide/basics/machine_translation/index.html
按照这个文档写的代码有同样的问题

**Comment by zhaowenfeng555** [comment]
06.understand_sentiment

**Comment by zhaowenfeng555** [comment]
train_conv.py

**Comment by zhaowenfeng555** [comment]
![image](https://user-images.githubusercontent.com/46885604/104156031-4a2d3f80-5423-11eb-98b4-af007e07c72a.png)

**Comment by zhaowenfeng555** [comment]
这个得 infer 报错

**Comment by lfchener** [comment]
请使用 paddle >= 1.8.0 的版本，并参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/user_guides/nlp_case/understand_sentiment/README.cn.html
